apiVersion: v1
kind: Pod
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  containers:
    - name: mongo-express
      image: mongo-express
      ports:
        - containerPort: 8081
      env:
        - name: ME_CONFIG_MONGODB_AUTH_USERNAME 
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: ME_CONFIG_MONGODB_AUTH_USERNAME
        - name: ME_CONFIG_MONGODB_AUTH_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: ME_CONFIG_MONGODB_AUTH_USERNAME
        - name: ME_CONFIG_MONGODB_AUTH_DATABASE 
          value: mongo-Service