apiVersion: v1
kind: Service
metadata: 
  name: mongo-Service
  labels:
    app: demo
    type: backend
spec: 
  ports:
    - port: 8080
      targetPort: 27017
  selector:
      app: demo
      type: backend
    


