apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-Deployment
  labels:
    app: demo
    type: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
      type: backend
  template:
      metadata:
        name: mongodb
        labels:
          app: demo
          type: backend
      spec:
       containers:
        - name: mongodb
          image: mongodb
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_PASSWORD