apiVersion: v1
kind: Service
metadata: 
  name: mongo-express-service
spec: 
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30002
  selector:
      app: mongo-express
    


