apiVersion: v1
kind: Service
metadata: 
  name: mongo-express-Service
  labels:
    app: demo
    type: backend
spec: 
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30002
  selector:
      app: demo
      type: backend
    


